apiVersion: v1
kind: Pod
metadata:
  name: no-restart-pod
spec:
  restartPolicy: Never
  initContainers:
  - name: wait-for-db
    image: busybox
    command: ['sh', '-c']
    args:
    - |
      for i in $(seq 1 5); do
        if nslookup nonexistent-db; then exit 0; fi
        echo "Attempt $i/5 failed"
        sleep 2
      done
      exit 1
  containers:
  - name: app
    image: nginx