apiVersion: v1
kind: Pod
metadata:
  name: fixed-pod
spec:
  initContainers:
  - name: wait-for-db
    image: busybox
    command: ['sh', '-c']
    args:
    - |
      for i in $(seq 1 10); do
        if nslookup nonexistent-db; then
          echo "Service found!"
          exit 0
        fi
        echo "Attempt $i/10 failed, retrying..."
        sleep 3
      done
      echo "Service not found after 10 attempts, giving up"
      exit 1
  containers:
  - name: app
    image: nginx
    ports:
    - containerPort: 80