apiVersion: v1
kind: Pod
metadata:
  name: fast-eviction
spec:
  tolerations:
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 10
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 10
  containers:
  - name: nginx
    image: nginx
