apiVersion: v1
kind: Pod
metadata:
  name: readiness-test
  labels:
    app: web
spec:
  containers:
  - name: app
    image: hashicorp/http-echo
    args:
    - "-text=Ready"
    - "-listen=:8080"
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 2
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 2
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5