apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: default-app
  template:
    metadata:
      labels:
        app: default-app
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 100m
