apiVersion: v1
kind: Pod
metadata:
  name: projected-secret
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Password:"; cat /secrets/db-pass; echo ""; sleep 10; done']
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
  volumes:
  - name: secret-volume
    projected:
      sources:
      - secret:
          name: db-credentials
          items:
          - key: password
            path: db-pass
            mode: 0400  # Read-only for owner