apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limits
  namespace: resource-test
spec:
  limits:
  - max:
      memory: "512Mi"
    min:
      memory: "64Mi"
    default:
      memory: "256Mi"
    defaultRequest:
      memory: "128Mi"
    type: Container
