apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
spec:
  containers:
  - name: hog
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "800M"]
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "1Gi"
