apiVersion: v1
kind: Service
metadata:
  name: web-backend-sticky
spec:
  selector:
    app: web-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 80
    targetPort: 80
